/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projetoindividualyoshi;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author educa
 */
public class TelaProjeto extends javax.swing.JFrame {

    /**
     * Creates new form TelaProjeto
     */
    public TelaProjeto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMedia = new javax.swing.JLabel();
        lbMinMem = new javax.swing.JLabel();
        lbMedia1 = new javax.swing.JLabel();
        lbMax1 = new javax.swing.JLabel();
        lbMin1 = new javax.swing.JLabel();
        lbMedia2 = new javax.swing.JLabel();
        lbMax2 = new javax.swing.JLabel();
        lbMin2 = new javax.swing.JLabel();
        lbMax = new javax.swing.JLabel();
        lbValorCpu = new javax.swing.JLabel();
        lbValorDisco = new javax.swing.JLabel();
        lbValorMemoria = new javax.swing.JLabel();
        lbMinCpu = new javax.swing.JLabel();
        lbMinDisco = new javax.swing.JLabel();
        lbMaxDisco = new javax.swing.JLabel();
        lbMaxMem = new javax.swing.JLabel();
        lbMaxCpu = new javax.swing.JLabel();
        lbMediaCpu = new javax.swing.JLabel();
        pbBarra1 = new javax.swing.JProgressBar();
        pbBarra2 = new javax.swing.JProgressBar();
        pbBarra3 = new javax.swing.JProgressBar();
        lbCpu = new javax.swing.JLabel();
        lbDisco = new javax.swing.JLabel();
        lbMemoria = new javax.swing.JLabel();
        btAcao1 = new javax.swing.JButton();
        lbMin = new javax.swing.JLabel();
        lbMediaDisco = new javax.swing.JLabel();
        lbMediaMem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMedia.setText("Média");

        lbMinMem.setText("0");

        lbMedia1.setText("Média");

        lbMax1.setText("Max");

        lbMin1.setText("Min");

        lbMedia2.setText("Média");

        lbMax2.setText("Max");

        lbMin2.setText("Min");

        lbMax.setText("Max");

        lbValorCpu.setText("?");

        lbValorDisco.setText("?");

        lbValorMemoria.setText("?");

        lbMinCpu.setText("0");

        lbMinDisco.setText("0");

        lbMaxDisco.setText("0");

        lbMaxMem.setText("0");

        lbMaxCpu.setText("0");

        lbMediaCpu.setText("0");

        lbCpu.setText("CPU");

        lbDisco.setText("DISCO");

        lbMemoria.setText("MEMÓRIA");

        btAcao1.setText("Fazer leitura dos dados");
        btAcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcao1ActionPerformed(evt);
            }
        });

        lbMin.setText("Min");

        lbMediaDisco.setText("0");

        lbMediaMem.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbValorCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMinCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDisco)
                                    .addComponent(lbValorDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lbMedia1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lbMediaDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMaxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMax, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lbMediaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbMaxCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMedia2)
                        .addGap(18, 18, 18)
                        .addComponent(lbMax2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbValorMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMinMem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMediaMem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaxMem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pbBarra3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pbBarra2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pbBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btAcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMax, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMinCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMediaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaxCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pbBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMedia1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisco))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMediaDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValorDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pbBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMemoria)
                    .addComponent(lbMin2)
                    .addComponent(lbMedia2)
                    .addComponent(lbMax2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMinMem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMediaMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaxMem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pbBarra3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAcao1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Variáveis Globais
    //CPU
    Integer contadorCpu = 0;
    Integer menorValorCpu = 100;
    Integer maiorValorCpu = 0;
    Integer valorTotalCpu = 0;
    
    //DISCO
    Integer contadorDisco = 0;
    Integer menorValorDisco = 100;
    Integer maiorValorDisco = 0;
    Integer valorTotalDisco = 0;
            
    //MEMORIA
    Integer contadorMem = 0;
    Integer menorValorMem = 8;
    Integer maiorValorMem = 0;
    Integer valorTotalMem = 0;
    
    private void btAcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcao1ActionPerformed

        //Criação dos valores aleatórios
        Integer valorCpu = ThreadLocalRandom.current().nextInt(0, 101);
        Integer valorDisco = ThreadLocalRandom.current().nextInt(0, 101);
        Integer valorMemoria = ThreadLocalRandom.current().nextInt(0, 9);

        //Configurações e valores das barras
        //Valor Barra 1
        pbBarra1.setString(valorCpu.toString());
        pbBarra1.setValue(valorCpu);

        //Config Barra 1
        //       pbBarra1.setStringPainted(true);
        //       pbBarra1.setForeground(Color.black);
        pbBarra1.setMinimum(0);
        pbBarra1.setMaximum(100);

        //Valor Barra 2
        pbBarra2.setString(valorDisco.toString());
        pbBarra2.setValue(valorDisco);

        //Config Barra 2
        //       pbBarra2.setStringPainted(true);
        //       pbBarra2.setForeground(Color.black);
        pbBarra2.setMinimum(0);
        pbBarra2.setMaximum(100);

        //Valor Barra 3
        pbBarra3.setString(valorMemoria.toString());
        pbBarra3.setValue(valorMemoria);

        //Config Barra 3
        //       pbBarra3.setStringPainted(true);
        //       pbBarra3.setForeground(Color.black);
        pbBarra3.setMinimum(0);
        pbBarra3.setMaximum(8);

        //Colocando os valores nas Labels
        lbValorCpu.setText(valorCpu.toString() + "%");
        lbValorDisco.setText(valorDisco.toString() + "%");
        lbValorMemoria.setText(valorMemoria.toString() + " GB");

        //Menor, Maior e Média Valor Lido Cpu

        if (valorCpu > maiorValorCpu) {
            maiorValorCpu = valorCpu;
            lbMaxCpu.setText(maiorValorCpu.toString());

        }
        if (valorCpu < menorValorCpu) {
            menorValorCpu = valorCpu;
            lbMinCpu.setText(menorValorCpu.toString());

        }

        valorTotalCpu += valorCpu;
        contadorCpu += 1;
        Double mediaCpu = Double.valueOf(valorTotalCpu) / Double.valueOf(contadorCpu);
        String mediaStringCpu = String.format("%.2f", mediaCpu);
        lbMediaCpu.setText(mediaStringCpu);

        //Menor, Maior e Média Valor Lido Disco

        if (valorDisco > maiorValorDisco) {
            maiorValorDisco = valorDisco;
            lbMaxDisco.setText(maiorValorDisco.toString());

        }
        if (valorDisco < menorValorDisco) {
            menorValorDisco = valorDisco;
            lbMinDisco.setText(menorValorDisco.toString());

        }

        valorTotalDisco += valorDisco;
        contadorDisco += 1;
        Double mediaDisco = Double.valueOf(valorTotalDisco) / Double.valueOf(contadorDisco);
        String mediaStringDisco = String.format("%.2f", mediaDisco);
        lbMediaDisco.setText(mediaStringDisco);

        //Menor, Maior e Média Valor Lido Memória

        if (valorMemoria > maiorValorMem) {
            maiorValorMem = valorMemoria;
            lbMaxMem.setText(maiorValorMem.toString());

        }
        if (valorMemoria < menorValorMem) {
            menorValorMem = valorMemoria;
            lbMinMem.setText(menorValorMem.toString());

        }

        valorTotalMem += valorMemoria;
        contadorMem += 1;
        Double mediaMem = Double.valueOf(valorTotalMem) / Double.valueOf(contadorMem);
        String mediaStringMem = String.format("%.2f", mediaMem);
        lbMediaMem.setText(mediaStringMem);

    }//GEN-LAST:event_btAcao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcao1;
    private javax.swing.JLabel lbCpu;
    private javax.swing.JLabel lbDisco;
    private javax.swing.JLabel lbMax;
    private javax.swing.JLabel lbMax1;
    private javax.swing.JLabel lbMax2;
    private javax.swing.JLabel lbMaxCpu;
    private javax.swing.JLabel lbMaxDisco;
    private javax.swing.JLabel lbMaxMem;
    private javax.swing.JLabel lbMedia;
    private javax.swing.JLabel lbMedia1;
    private javax.swing.JLabel lbMedia2;
    private javax.swing.JLabel lbMediaCpu;
    private javax.swing.JLabel lbMediaDisco;
    private javax.swing.JLabel lbMediaMem;
    private javax.swing.JLabel lbMemoria;
    private javax.swing.JLabel lbMin;
    private javax.swing.JLabel lbMin1;
    private javax.swing.JLabel lbMin2;
    private javax.swing.JLabel lbMinCpu;
    private javax.swing.JLabel lbMinDisco;
    private javax.swing.JLabel lbMinMem;
    private javax.swing.JLabel lbValorCpu;
    private javax.swing.JLabel lbValorDisco;
    private javax.swing.JLabel lbValorMemoria;
    private javax.swing.JProgressBar pbBarra1;
    private javax.swing.JProgressBar pbBarra2;
    private javax.swing.JProgressBar pbBarra3;
    // End of variables declaration//GEN-END:variables
}
